config/routes.rb
Rails.application.routes.draw do
  root :to => 'sections#index'

  resources :sections do
    resources :lessons
  end

  resources :lessons do
    resources :chapters
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :lesson
  belongs_to :section

  validates :lesson_id, :presence => true
  validates :text, :presence => true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  has_many :chapters

  validates :lesson_title, :presence => true
  validates :number, :presence => true
  validates :section_id, :presence => true

  scope :created_today, -> { where("created_at >=?", Time.now.beginning_of_day)}
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :lessons
  has_many :chapters

  validates :section_title, :presence => true

  scope :section_title, -> (section_title_parameter) { where(section_title: section_title_parameter) }

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def index
    @lesson = Lesson.find(params[:lesson_id])
    @chapters = @lesson.chapters.all
    @section = @lesson.section
    @chapter = Chapter.find(params[:lesson_id])
  end

  def show
    @chapter = Chapter.find(params[:lesson_id])
    render :show
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @section = Section.find(params[:section_id])
    @lessons = @section.lessons.all
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.all 
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      flash[:notice] = "Section successfully added!"
      redirect_to '/'
    else
      flash[:alert] = "Section not added, can't be blank"
      render :new
    end
  end

  private
    def section_params
      params.require(:section).permit(:section_title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chapters/index.html.erb
<h3><%= link_to @section.section_title, section_lessons_path(@lesson)%> / <%= @lesson.lesson_title %></h3>

<% @chapters.each do |chapter| %>

  <p><%= link_to chapter.title, lesson_chapter_path(@chapter.lesson_id, @section) %></p>
<% end %>

app/views/chapters/show.html.erb
<h1><%= @chapter.title %></h1>

<p><%= @chapter.text %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <% content_for(:navbar) do %>
      <li><a href="/">Home</a></li>
      <li><a href="something/else">Something else</a></li>
      <li><a href="etc">Etc.</a></li>
    <% end %>

    <nav class="navbar navbar-fixed-top navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapsable">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapsable">
          <ul class="nav navbar-nav foo" id="menu">

            <li class="active"><a href="/">Home</a></li>
            <li><a href="/about-us">About Us</a></li>
            <li>
              <a href="/contact">
                <span class='glyphicon glyphicon-hand-right'></span>
                Contact Us!
              </a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Stuff <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li class="dropdown-header">Great stuff!</li>
                <li><a href="/one">One</a></li>
                <li><a href="/two">Two</a></li>
                <li><a href="/three">Three</a></li>
                <li class="divider"></li>
                <li><a href="/admin">Admin Dashboard</a></li>
                <li><a href="/admin/users">Users</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right" align="right">
            <li><a href="/logout">Log Out</a></li>
          </ul>
        </div>
      </div>
    </nav> -->
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    
    <%= yield %>
  </body>
</html>

app/views/lessons/index.html.erb
<h1><%= @section.section_title %></h1>

<% @section.lessons.each do |lesson| %>
  <p>
    <%= link_to lesson.lesson_title, lesson_chapters_path(lesson) %>
  </p>
<% end %>

app/views/sections/index.html.erb
<% content_for(:title, "Section | Learn How To Program") %>

<h1>Courses</h1><h4><em><%= link_to "Create a New Course", new_section_path %></em></h4>
<% @sections.each do |section| %>
  <p><%= link_to section.section_title, section_lessons_path(section) %></p>
<% end %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<% if @section.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% @section.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @section do |f| %>
  <%= f.label :section_title %>
  <%= f.text_field :section_title %>
  <%= f.submit  %>
<% end %>